# docker-compose.yaml
version: '3.8'
networks:
  jenkins-network:
    name: jenkins
volumes:
  data:
    name: jenkins-data
  certs:
    name: jenkins-docker-certs
services:
  dind:
    container_name: jenkins-docker
    image: docker:dind
    privileged: true
    restart: unless-stopped
    networks:
      jenkins-network:
        aliases:
          - docker
    volumes:
      - data:/var/jenkins_home
      - certs:/certs/client
    environment:
      - DOCKER_TLS_CERTDIR=/certs
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    restart: unless-stopped
    networks:
      - jenkins-network
    ports:
      - 8085:8080
      - 50000:50000
    volumes:
      - data:/var/jenkins_home
      - certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

#  localstack:
#    container_name: localstack
#    image: localstack/localstack
#    ports:
#      - "127.0.0.1:4566:4566"            # LocalStack Gateway
#      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
#    environment:
#      - DEBUG=debug
#      - PERSISTENCE=true
#      - LAMBDA_EXECUTOR=local
#      - DOCKER_HOST=unix:///var/run/docker.sock
#    volumes:
#      - /var/lib/localstack:/var/lib/localstack
#      - /var/run/docker.sock:/var/run/docker.sock